qiime2/q2-types

q2_types/_feature_data.py

Thanks @ElDeveloper for catching this!

BUG: prevent index type casting when reading TSV files

---

q2_types/plugin_setup.py

ENH: adds citation_text and user_support_text

---

setup.py

Package data contains unit test data for `qiime.tests` and `qiime.distance_matrix.tests`.

BUG: add package data to setup.py

---

q2_types/feature_data/_transformer.py

@ebolyen or @thermokarst, want to review this one?

BUG: fixes broken transformer

---

q2_types/feature_table/_transformer.py

The formats are incompatible w.r.t certain types of axis metadata, and we need to support both formats and converting between them. QIIME 2 can ignore axis metadata because it is stored as separate artifacts.

BUG: ignore axis metadata for BIOM v1 and v2 readers/writers

---

q2_types/feature_data/_transformer.py

These will support merging of:
* two FeatureData[Sequence] artifacts
* two FeatureData[Taxonomy] 
(Those are independent merge operations - this is a little confusing to describe.)

ENH: adds transformers

---

q2_types/feature_table/_transformer.py
q2_types/feature_table/tests/test_transformer.py

Fixes #73
```python
In [1]: import qiime
In [2]: a = qiime.Artifact.load('table.qza')
In [3]: import pandas as pd
In [4]: df = a.view(pd.DataFrame)
In [5]: b = qiime.Artifact.import_data("FeatureTable[Frequency]", df)
In [6]: import biom
In [7]: a.view(biom.Table) == b.view(biom.Table)
Out[7]: True
```

ENH: adds pd.DataFrame to biom transformers

---

q2_types/feature_table/_transformer.py
q2_types/feature_table/tests/test_transformer.py

ENH: pd.Dataframe->biom.Table index type guard

---

q2_types/per_sample_sequences/_transformer.py

This allows paired-end data to be used in contexts in which the reverse
reads can be ignored for the purposes of a method. This effectively
"downcasts" the paired-end sequences into single-end sequences.
@gregcaporaso this is what we discussed earlier on Friday, and it will allow us to use `q2-demux:summarize` on paired-end data without changing anything other than the semantic type annotation. It will also make it easy to compare `dada2:denoise-single` and `dada2:denoise-paired` on the same `EMPPairedEndSequences` artifact. This transformer basically just discards the reverse reads in the directory and MANIFEST.

ENH: add transformer from paired end to single end

---

q2_types/per_sample_sequences/_transformer.py

Depends on https://github.com/qiime2/qiime2/pull/274

BUG: fix import for cross-device fs

---

q2_types/per_sample_sequences/_transformer.py

"... it that appears ..." -> "... it appears that ..."

MAINT: Fix typo "that"

---

setup.py

BUG: Missing package data

---

q2_types/feature_data/_transformer.py
q2_types/feature_data/tests/test_transformer.py

BUG: Fix pd.Series -> DNAFASTAFormat Transformer

---

q2_types/per_sample_sequences/_format.py
q2_types/per_sample_sequences/tests/test_format.py

pair programmed with @thermokarst 
fixes #143 
fixes #126 
fixes `disallow subdirectories`

BUG: adds validate to SampleData[*Quality] formats

---

q2_types/per_sample_sequences/__init__.py
q2_types/per_sample_sequences/_type.py
q2_types/per_sample_sequences/tests/test_type.py

It's been a while since I've added a new type - let me know if I'm missing anything here.

ENH: adds JoinedSequencesWithQuality

---

q2_types/ordination/tests/test_transformer.py
q2_types/sample_data/_transformer.py
q2_types/sample_data/tests/test_transformer.py

See qiime2/qiime2#359 for details.

MAINT: new Metadata updates

---

ci/recipe/meta.yaml

As per a conversation with @ebolyen in the forum, I'm bumping the minimum version of scikit-bio to see if hell breaks loose. 🌋 :rage4:

BLD: Bump the scikit-bio minimum version

---

q2_types/feature_table/_transformer.py
q2_types/feature_table/tests/test_transformer.py

added biom -> metadata transformers and tests

---

q2_types/feature_table/__init__.py
q2_types/feature_table/_format.py
q2_types/feature_table/_transformer.py
q2_types/feature_table/tests/test_format.py
q2_types/feature_table/tests/test_transformer.py

Three logical commits, rebase.

MAINT: BIOMV100 cleanup

---

q2_types/per_sample_sequences/tests/test_transformer.py

BUG: typo in test

---

q2_types/feature_table/__init__.py
q2_types/feature_table/_type.py
q2_types/feature_table/tests/test_type.py

This variant is going to be used for q2-classo, a plugin for constraint lasso. 
It represents transformed/coded data, as an alternative to composition which only positive values. 
cc @ebolyen

NEW: add Design variant to FeatureTable

---

q2_types/per_sample_sequences/_format.py

BUG: Goes along with qiime2/q2-demux#118

---

q2_types/feature_data/_transformer.py
q2_types/feature_data/tests/test_transformer.py

added blast6format to metadata transformer

---

q2_types/per_sample_sequences/_format.py

A very small edit based on a renamed function in pandas.
Closes #290 
EDIT: :shipit:

iteritems -> items to close #290

---

q2_types/feature_data/_type.py

Partially addresses https://github.com/bokulich-lab/q2-moshpit/issues/43

add variant type for q2-moshpit
