qiime2/q2-types

- q2_types/tests/__init__.py
Once we start using pkg_resources to locate test data files, tests will need to be in a package.
> MAINT: make q2_types.tests a package

- setup.py
The current version of master depends on a newer version of the framework. This was overlooked in the last commit.
> MAINT/BUG: bumps minimum framework dependency version

- q2_types/feature_data/_transformer.py
The `PairedDNAIterator` -> `PairedDNASequencesDirectoryFormat` transformer was not using `write_data` to set it's contents. Now it does.
> BUG: PairedDNAIterator->PairedDNASeqDirFmt uses write_data

- q2_types/feature_data/_transformer.py
`DNAIterator` wraps a generator (so that transformer registration works). The `DNAIterator` -> `DNAFastaFormat` transformer was not accessing the wrapped generator. Now it does.
> BUG: DNAIterator -> DNAFASTAFormat now uses generator

- .travis.yml
Explicitly set the matplotlib backend to `Agg`, due to a QT dependency mismatch in conda's distribution of matplotlib.
> BUG: bootstrap matplotib config

- q2_types/per_sample_sequences/__init__.py
These will be used as output types in `q2-demultiplex`.
> ENH: makes iterators importable

- q2_types/distance_matrix/_format.py
- q2_types/distance_matrix/_type.py
- q2_types/feature_data/_format.py
- q2_types/feature_data/_type.py
- q2_types/feature_table/_format.py
- q2_types/feature_table/_type.py
- q2_types/ordination/_format.py
- q2_types/ordination/_type.py
- q2_types/per_sample_sequences/_format.py
- q2_types/per_sample_sequences/_type.py
- q2_types/reference_features/_format.py
- q2_types/reference_features/_type.py
- q2_types/sample_data/_format.py
- q2_types/sample_data/_type.py
- q2_types/tree/_format.py
- q2_types/tree/_type.py
Removes duplicate `BIOMV100DirFmt` registration.
Adds explicit format registration to the plugin object as per qiime2/qiime2/pull/159.
***This will fail testing until the `qiime2` PR is merged.***
Resolves #56
> FIX/REF: Remove dupe BIOM registration, register formats

- q2_types/feature_data/__init__.py
- q2_types/feature_data/_transformer.py
- q2_types/feature_data/tests/test_transformer.py
`Sequence` has `DNAIterator` but `AlignedSequence` had no `AlignedDNAIterator`. This PR redresses that imbalance.
> ENH: added feature_data.AlignedDNAIterator

- q2_types/feature_data/_transformer.py
Fixes #101 
Also makes the transformers work as long is the constructor argument to `DNAIterator` is iterable. (scikit-bio always needed a generator, and now `DNAIterator` returns a generator after calling `iter`)
> BUG: Fixes DNAIterator to conform to ABC

- q2_types/tree/__init__.py
- q2_types/tree/_type.py
- q2_types/tree/tests/test_type.py
This pull request is for introducing another tree data type `Hierarchy`.
The main motivation behind this is there are other instances of trees other than `Phylogeny` such as  hierarchical clusterings.  And using `Phylogeny` to represent these data types are incredibly misleading.  This is critical for reducing confusion for performing analyses with Gneiss, which can operate directly on `Phylogeny` and `Hierarchy` types.
> ENH: Adding in hierarchy type

- q2_types/per_sample_sequences/__init__.py
- q2_types/per_sample_sequences/_format.py
- q2_types/per_sample_sequences/_transformer.py
- q2_types/per_sample_sequences/tests/data/absolute_manifests/jagged-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests/long-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests/paired-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests/single-MANIFEST
- q2_types/per_sample_sequences/tests/data/no-data-MANIFEST
- q2_types/per_sample_sequences/tests/data/relative_manifests/jagged-MANIFEST
- q2_types/per_sample_sequences/tests/data/relative_manifests/long-MANIFEST
- q2_types/per_sample_sequences/tests/data/relative_manifests/paired-MANIFEST
- q2_types/per_sample_sequences/tests/data/relative_manifests/single-MANIFEST
- q2_types/per_sample_sequences/tests/test_format.py
- q2_types/per_sample_sequences/tests/test_transformer.py
All changes in this commit are related to the "per-sample sequence" formats.
Several changes:
- Comments and blank lines are now supported in "per-sample sequence" manifest formats, including sniffers and transformers.
- Duplicate samples are now additionally detected and disallowed in "relative path" manifest formats (previously this validation only happened in the "absolute path" manifest formats).
- Error messages reported by transformers are both more precise and accurate.
- Refactored sniffer and transformer code to reduce redundancy and perform consistent validation and parsing in all sniffers/transformers.
- Added unit tests, increased coverage to 100% for "per-sample sequence" formats, and made existing unit tests and test data more robust.
Fixes #126.
Fixes #129.
Fixes #132. …
> ENH/BUG/MAINT: support comments/blank lines and better validation in "per-sample sequence" formats

- q2_types/per_sample_sequences/__init__.py
- q2_types/per_sample_sequences/_transformer.py
- q2_types/per_sample_sequences/tests/test_transformer.py
Removes `q2_types.per_sample_sequences.PerSampleDNAIterators` and `q2_types.per_sample_sequences.PerSamplePairedDNAIterators` view types, along with their corresponding transformers. As part of discussion in #129 and #130 it was found that these view types never actually worked and weren't being used anywhere. Even getting them to work raises another problem: file descriptor limit.
New view types can be added in the future that avoid the file descriptor limit.
> BUG: remove PerSampleDNAIterators and PerSamplePairedDNAIterators

- q2_types/feature_data/_format.py
- q2_types/feature_data/tests/test_format.py
We didn't turn this into a validate because fasta is a much more flexible format so it didn't seem worth the time at this point.
> HACK: allow empty fasta files

- q2_types/per_sample_sequences/_format.py
- q2_types/per_sample_sequences/tests/test_format.py
This change is necessary to support the closed-reference OTU picking API in q2-ninja-ops, which returns a QIIME1DemuxFormat file of sequences that failed to hit the reference. It is possible in some cases for there to be zero failures.
This change is similar to allowing empty `FeatureData[Sequence]` artifacts, which is required by q2-vsearch's closed-reference OTU picking API.
> ENH: support empty files in QIIME1DemuxFormat

- q2_types/sample_data/_format.py
- q2_types/sample_data/tests/data/alpha-diversity-with-metadata.tsv
- q2_types/sample_data/tests/test_transformer.py
Fixes #182 
Allow for greater than 2 columns in alpha diversity file.
> Fixes: #182

- ci/recipe/meta.yaml
This bumps skbio to 0.5.4 (which has not been released yet but will be within a day or so).
Skbio 0.5.4 is needed to support: https://github.com/qiime2/q2-diversity/pull/217, which
updates the ordination class in `q2-diversity` to support new scikit-bio's fast heuristic pcoa method.
TO-DO:
> Bump the scikit-bio version to 0.5.4 (containing new pcoa api)

- q2_types/sample_data/_transformer.py
- q2_types/sample_data/tests/test_transformer.py
AlphaDiversityFormat to Metadata transformer now supports multi-column alpha diversity data. Previously only the first data column would be included when viewed as Metadata. 
For example, `qiime metadata tabulate --m-input-file richness-better.qza --o-visualization richness-better.qzv` before:
and after:
> ENH: multi-column alpha diversity as metadata

- q2_types/per_sample_sequences/_transformer.py
- q2_types/per_sample_sequences/tests/test_format.py
- versioneer.py
Minor updates for compliance with flake8 v3.6, as discussed in qiime2/qiime2#415
Note: flake8 has been disabled in versioneer.py.
> Update for flake8 v3.6

- q2_types/per_sample_sequences/__init__.py
- q2_types/per_sample_sequences/_format.py
- q2_types/per_sample_sequences/_transformer.py
- q2_types/per_sample_sequences/tests/data/absolute_manifests_v2/missing-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests_v2/multicol-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests_v2/numeric-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests_v2/paired-MANIFEST
- q2_types/per_sample_sequences/tests/data/absolute_manifests_v2/single-MANIFEST
- q2_types/per_sample_sequences/tests/test_format.py
- q2_types/per_sample_sequences/tests/test_transformer.py
> ENH: Metadata-compatible manifest formats

- ci/recipe/meta.yaml
closes #215: Pin `scipy` to >=1.0.0,<1.3.0 to prevent import bug in `statsmodels`
> HACK: Pin scipy to older version

- ci/recipe/meta.yaml
Reverts qiime2/q2-types#216
Statsmodels has finally been released!
> Revert "HACK: Pin scipy to older version"

- q2_types/feature_table/__init__.py
- q2_types/feature_table/_format.py
- q2_types/feature_table/_transformer.py
- q2_types/feature_table/tests/test_format.py
- q2_types/feature_table/tests/test_transformer.py
Dropping BIOMV100 support.
Related to discussion in https://github.com/biocore/biom-format/issues/816
We can roll this back in if we need to _after_ scipy 1.3.1, but luckily in the meantime users can be instructed on how to set up a conda env to convert to 2.1.0 on their own.
> MAINT: Remove BIOMV100 support

- ci/recipe/meta.yaml
Recent OpenBLAS versions have fixed the AVX situation, so unpin.
https://github.com/conda-forge/openblas-feedstock/issues/64
https://github.com/xianyi/OpenBLAS/pull/2111
> Revert "BUG: pin OpenBLAS for SkylakeX+ processors (#213)"

- q2_types/sample_data/tests/test_transformer.py
Pandas has deprecated the `from_csv` method in favor of `read_csv` as of `v0.21.0`. This change is needed to make plugins pass unit tests utilizing the newest version of pandas `v0.25.1`. Fixes issue #227
> MAINT: removed use of deprecated method from_csv

- ci/recipe/meta.yaml
fixes qiime2/q2-sample-classifier#164
we'll want to [open this pin up to future versions](https://github.com/qiime2/q2-types/issues/232) in 2020.1
> HACK: hard pins matplotlib at 3.1.0

- ci/recipe/meta.yaml
closes #232, matplotlib 3.1.3 is producing correct heatmaps.
> HACK: Revert pin added in #233

- q2_types/feature_data/_format.py
- q2_types/feature_data/tests/data/not-dna-sequences.fasta
- q2_types/feature_data/tests/test_format.py
Implements the improvements discussed at the end of #214. Namely we now display to the user the first invalid character on the first invalid line.
> MAINT: Improve error message for invalid characters in DNAFASTAFormat

- q2_types/per_sample_sequences/_format.py
- q2_types/per_sample_sequences/_transformer.py
- q2_types/per_sample_sequences/_util.py
- q2_types/per_sample_sequences/tests/test_format.py
- q2_types/per_sample_sequences/tests/test_transformer.py
Fixes #209
Related to https://github.com/qiime2/q2-quality-control/pull/52/
---
Missing unit tests
> IMP: transformers SingleLanePerSample... to Casava

- q2_types/per_sample_sequences/tests/data/metadata.yml.txt
- q2_types/per_sample_sequences/tests/data/single_end_data/MANIFEST.txt
- q2_types/per_sample_sequences/tests/test_format.py
Adds a test for the behavior described in #218. I made sure the test will work properly when and if qiime2/qiime2#538 is merged.
> BUG: Add test asserting that filenames are more fully regexed

- q2_types/feature_data/_transformer.py
- q2_types/feature_data/tests/test_transformer.py
This adds transformers needed for https://github.com/qiime2/q2-feature-table/issues/232 and https://github.com/qiime2/q2-alignment/issues/70
> IMP: additional aligned sequence transformers

- q2_types/feature_data/_format.py
- q2_types/feature_data/tests/test_format.py
Start doing for `AlignedDNAFASTAFormat` what #214 did for `DNAFASTAFormat`
> IMP: Implement AlignedDNAFASTAFormat validation

- q2_types/feature_data/__init__.py
- q2_types/feature_data/_format.py
@misialq - what do you think about exporting the `AlignedFASTAFormatMixin`? Also, I dropped the `FASTAFormat` from the plugin format registration hook, since at present we don't intend for any consumers to actually work with this base format directly.
> maint: cleanup fasta exports and registrations

- q2_types/distance_matrix/_type.py
- q2_types/feature_data/_type.py
- q2_types/feature_table/_type.py
- q2_types/feature_table/tests/test_type.py
- q2_types/multiplexed_sequences/_type.py
- q2_types/ordination/_type.py
- q2_types/per_sample_sequences/_type.py
- q2_types/sample_data/_type.py
- q2_types/tree/_type.py
- q2_types/tree/tests/test_type.py
This pull request depends on https://github.com/qiime2/qiime2/pull/655. 
This makes changes to tests to:
* handle new behavior associated with that PR (semantic types rather than type expressions are registered to formats for artifact classes), 
* to update to new parameter names (`directory_format` instead of `artifact_format`, though `artifact_format` is still supported when calling `Plugin.register_semantic_type_to_format`) 
* add a few artifact class descriptions and usage examples for initial testing purposes. 
In a development environment with the above `qiime2` branch installed, this can be tested as follows:
```python
from qiime2.sdk import PluginManager
pm = PluginManager()
pm.get_semantic_types()
pm.get_semantic_types()['Phylogeny[Rooted]'] …
```
> updates to artifact class registration

- q2_types/bowtie2/_types.py
- q2_types/distance_matrix/_type.py
- q2_types/feature_data/_type.py
- q2_types/feature_table/_type.py
- q2_types/multiplexed_sequences/_type.py
- q2_types/ordination/_type.py
- q2_types/sample_data/_type.py
- q2_types/tree/_type.py
Add annotations of artifact classes. This PR is primarily moving [artifact class descriptions from our static docs](https://docs.qiime2.org/2022.8/semantic-types/) to the descriptions on the artifact classes themselves.
> add artifact class annotations
